# Generated by Django 4.2.5 on 2023-09-24 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_usersubmitanswer_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmitanswer',
            name='score',
        ),
        migrations.RemoveField(
            model_name='usersubmitanswer',
            name='user',
        ),
        migrations.AddField(
            model_name='usersubmitanswer',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.quizquestions'),
        ),
        migrations.AddField(
            model_name='usersubmitanswer',
            name='right_answer',
            field=models.CharField(default='', max_length=200),
        ),
    ]
