# Generated by Django 4.2.5 on 2023-09-24 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_remove_usersubmitanswer_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmitanswer',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.quizcategory'),
        ),
        migrations.AddField(
            model_name='usersubmitanswer',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
