# Generated by Django 4.2.5 on 2023-10-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_certifiedalready_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifiedalready',
            name='date_issue',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
